[project]
name = "lambda-bot"
version = "0.1.0"
description = "Add your description here"
readme = "README.md"
requires-python = ">=3.12"
dependencies = [
    "pydantic-settings>=2.9.1",
    "slack-bolt>=1.23.0",
]

[dependency-groups]
dev = [
    "pyright>=1.1.401",
]
